/*SEARCH AND JOINS*/

use oficina;

/* Data recover with select statments*/
select * from clients;

select idVehicle, idClient, model, brand, model_year, plate 
from vehicle;

/* Filters using WHERE */
select count(*) 
from mechanic
where mSpecialty = 'Geral';

select * from service_order
where deliveryForecast != deliveryDate
order by deliveryDate;

/* Derivative attributes generated by expressions */
select idPart as ID, partName as PEÇA, partValue as PREÇO, round(partValue*0.10, 2) as MARGEM
from part;

/* Order by*/
select idVehicle, brand, model, model_year, vehicle.idClient, concat(firstName,' ', lastName) as DONO
from vehicle join clients
on clients.idClient = vehicle.idClient
order by brand, model, DONO;


/* group by & having */
select idClient
from vehicle
where count(idClient);

select idTeam, sum(SO_Value) as FATURA
from service_order
group by idTeam
having FATURA > 1000.00
order by FATURA;


/* Joins for more complexe views of data */
select clients.idClient as ID, concat(firstName, ' ', lastName) as CLIENTE, SO_value as ValorServicos
from clients join vehicle
on clients.idClient = vehicle.idClient
	join service_order
	on vehicle.idVehicle = service_order.idVehicle
group by CLIENTE
order by CLIENTE;

